[package]
name = "myself"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbatis = "4.0.58"
rbdc = "0.1.23"
rbdc-sqlite = "0.1.17"
rbs = "0.1.15"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.25.0", features = ["full"] }
